openapi: 3.0.3
info:
  title: API REST
  version: "3.0.3"
paths:
  /add-events:
    post:
      tags:
        - event
      summary: Add a new event
      description: Add a new event
      operationId: addEvent
      responses:
        '201':
          description: Successful operation
        '400':
          description: Invalid input
  /display-events:
    get:
      tags:
        - event
      summary: Display events in chronological order
      description: Display events in chronological order
      operationId: displayChro
      responses:
        '200':
          description: successful operation
  /display-events/{person}:
    get:
      tags:
        - event
      summary: Display events in which someone participates in chronological order
      description: Display events in which someone participates in chronological order
      operationId: displayPerson
      parameters:
        - name: person
          in: path
          description: Person identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
  /add-participants/{event_name}/participants:
    post:
      tags:
        - event
      summary: Add a participant to a given event
      description: Add a participant to a given event
      operationId: addPartEvent
      parameters:
        - name: event_name
          in: path
          description: Event name
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid input supplied
  /import-csv:
    post:
      tags:
        - event
      summary: Import events from a csv file 
      description: Import events from a csv file 
      operationId: import
      responses:
        '200':
          description: successful operation
  /time/{person}:
    get:
      tags:
        - event
      summary: Get the time someone passed on an event
      description: Get the time someone passed on an event
      operationId: displayTime
      parameters:
        - name: person
          in: path
          description: Person identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
  /time-left/{date}:
    get:
      tags:
        - event
      summary: Get the time remaining before an event
      description: Get the time remaining before an event
      operationId: getTime
      parameters:
        - name: date
          in: path
          description: Date of the event
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
  
  
