name: Manual Action Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        working-directory: projet_cicd
        run: docker build . --file Dockerfile.dockerfile
