name: Tagged Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        working-directory: projet_cicd
        run: |
          version=$(echo "${GITHUB_REF}" | sed -n 's/refs\/tags\/v\(.*\)/\1/p')
          docker build . --file Dockerfile.dockerfile -t image-projet:latest
          docker push image-projet
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCLOUD_KEY }}
    
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: esirem

      - name: Configure Docker using GCLOUD
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push Docker images
        uses: docker/build-push-action@v3.3.1
        with:
          # Emplacement du Dockerfile
          file: projet_cicd/Dockerfile.dockerfile
          tags: europe-west1-docker.pkg.dev/esirem/esirem/4A_[ilc]/[wissocq]/[4A_ILC_CICD_PROJET]:${{ github.ref_name }}
          # Emplacement des fichiers 
          context: projet_cicd
          push: true
